Session slice
gaji-market/gaji-market pull request #93
Opened 2022-12-23 07:03 UTC by Sunn-y

2023-01-07 06:11 UTC, Sunn-y reviewed
save 하니까 자동으로 줄바꿈이 되어서 수정한 내용이 많아 보이네요 ㅠㅠ
제가 vs code setting을 두분과 맞춰야 할 것 같은데,
혹시 어떤 거 설정하셨나요?

2023-01-07 06:11 UTC, Sunn-y commented on front/src/pages/ProductView.jsx
> +        }}
모달 재사용을 위해 이유님이 작업하신 movePage 모달을 props로 넘겨주는 걸로 변경하였습니다.
혹시 다른 더 좋은 방법 있다면, 아니면 이 수정 내용이 이유님이 생각하신 방향과 다르다면 말씀해 주세요.
revert 하겠습니다.

2023-01-07 06:11 UTC, Sunn-y commented on front/src/pages/SignUp.jsx
> -  }, []);
Router에서 로그인 여부를 확인하는 로직을 추가하였기 때문에 위 로직은 실행될 일이 없습니다.
따라서 삭제하였습니다.

2023-01-09 10:47 UTC, ReturnReason commented on front/.env
> +REACT_APP_SESSION_LIMIT = "3600000"
> save 하니까 자동으로 줄바꿈이 되어서 수정한 내용이 많아 보이네요 ㅠㅠ 제가 vs code setting을 두분과 맞춰야 할 것 같은데, 혹시 어떤 거 설정하셨나요?

헙. 아마 프리티어의 printWidth 때문에 그런 것 같아요! 
`80` 사용하시면 제가 맞추겠습니다!

2023-01-09 10:47 UTC, ReturnReason commented on front/src/components/common/Modal.jsx
> +                <Button onClick={() => [confirmHandler(), setVisible(false)]}>
오 아닙니당 괜찮습니다! 추가해서 사용하시면 됩니다!

2023-01-09 10:55 UTC, ReturnReason requested changes
전체적으로 확인하시느라 고생하셨어요 👏👏

해당 부분은 제가 경험이 없어서 궁금합니다!
`JWT`는 보통 프론트에서 암호화해서 사용하는 건가요~?

2023-01-09 10:55 UTC, ReturnReason commented on front/src/pages/ProductView.jsx
> +        }}
오 저는 너무 좋습니당 👍👍

2023-01-09 12:35 UTC, vjvl95 commented on front/src/pages/Login.jsx
> -          //sessionStorage.setItem('userToken', res.token);
> session 에 관련된 내용은 sessionSlice에 있습니다.

아항 그렇군요 넵 감사합니다^^ sessionSlice에서 사용하겠습니다

2023-01-09 12:35 UTC, vjvl95 commented on front/src/pages/Login.jsx
> -  }, []);
> Router에서 로그인 여부를 확인하는 로직을 추가하였기 때문에 위 로직은 실행될 일이 없습니다. 따라서 삭제하였습니다.

잘하셨습니다^^

2023-01-09 12:35 UTC, vjvl95 commented on front/src/pages/MyPage.jsx
> -    } else getUserData();
> Router에서 로그인 여부를 확인하는 로직을 추가하였기 때문에 위 로직은 실행될 일이 없습니다. 따라서 삭제하였습니다.

넵^^ 감사합니다

2023-01-09 12:36 UTC, vjvl95 commented on front/src/pages/SignUp.jsx
> -  }, []);
> Router에서 로그인 여부를 확인하는 로직을 추가하였기 때문에 위 로직은 실행될 일이 없습니다. 따라서 삭제하였습니다.

굳굳

2023-01-09 12:39 UTC, vjvl95 commented on front/src/pages/Login.jsx
> +
> import 순서만 정리했습니다.

아하 그렇군요 혹시 import 정리하는 순서가 따로 있을까요?

2023-01-09 12:40 UTC, vjvl95 commented on front/src/pages/MyPage.jsx
> -            product;
printWidth속성이 다른거 같습니다.  한 줄로 있던게 내려왔네요

2023-01-09 12:40 UTC, vjvl95 commented on front/src/pages/MyPage.jsx
> -            product;
저는 80쓰고 있습니다

2023-01-09 13:00 UTC, Sunn-y commented on front/package.json
> +    "jwt-decode": "^3.1.2",
암호화는 제가 그냥 한겁니다! 일반적으로 저렇게 하는 지는 모르겠어요 ㅋㅋ 
그냥 비번 자체가 스토리지에 저장되는 게 좀 거시기 해서 했습니다 ㅋㅋ

2023-01-09 13:23 UTC, Sunn-y commented
> 전체적으로 확인하시느라 고생하셨어요 👏👏
> 
> 해당 부분은 제가 경험이 없어서 궁금합니다! `JWT`는 보통 프론트에서 암호화해서 사용하는 건가요~?

아닙니다! 일반적이지 않아요!
JWT는 누구나 까볼 수 있고, 안에 아이디랑 비밀번호가 들어있기 때문에 그냥 스토리지에 저장하면 위험할 것 같아서
암호화를 하여 저장한 겁니다.
그나마 조금 보안을 신경쓴다고 한건데, 저게 나은 방향인지는 잘 모르겠습니다.

2023-01-09 13:34 UTC, ReturnReason commented
> > 전체적으로 확인하시느라 고생하셨어요 👏👏
> > 해당 부분은 제가 경험이 없어서 궁금합니다! `JWT`는 보통 프론트에서 암호화해서 사용하는 건가요~?
> 
> 아닙니다! 일반적이지 않아요! JWT는 누구나 까볼 수 있고, 안에 아이디랑 비밀번호가 들어있기 때문에 그냥 스토리지에 저장하면 위험할 것 같아서 암호화를 하여 저장한 겁니다. 그나마 조금 보안을 신경쓴다고 한건데, 저게 나은 방향인지는 잘 모르겠습니다.

JWT에 비밀번호를 실어 보내나요..? 그렇다면 디코딩해서 말씀하신 것처럼 문제가 될 수 있을 것 같은데요ㅠㅠ
유저를 식별 가능할 수 있는 key라던가, id 같은 내용만 실어 보내야 하지 않나요??

2023-01-09 13:40 UTC, vjvl95 commented
> > > 전체적으로 확인하시느라 고생하셨어요 👏👏
> > > 해당 부분은 제가 경험이 없어서 궁금합니다! `JWT`는 보통 프론트에서 암호화해서 사용하는 건가요~?
> > 
> > 
> > 아닙니다! 일반적이지 않아요! JWT는 누구나 까볼 수 있고, 안에 아이디랑 비밀번호가 들어있기 때문에 그냥 스토리지에 저장하면 위험할 것 같아서 암호화를 하여 저장한 겁니다. 그나마 조금 보안을 신경쓴다고 한건데, 저게 나은 방향인지는 잘 모르겠습니다.
> 
> JWT에 비밀번호를 실어 보내나요..? 그렇다면 디코딩해서 말씀하신 것처럼 문제가 될 수 있을 것 같은데요ㅠㅠ 유저를 식별 가능할 수 있는 key라던가, id 같은 내용만 실어 보내야 하지 않나요??

비밀번호가 들어 있는건 맞습니다.. 근데 그걸 알아내는 방법은 secret키로 아이디 및 비밀번호가 생성되어서 secret키를 알지 못하면 비밀번호가 유출되는 일은 없을겁니다.  현재 저희 로직도 비밀번호가 변경되면 새로 토큰을 발급해주는 이유도 거기에 있습니다. 토큰에 비밀번호가 포함되어 있기 때문입니다.
https://www.youtube.com/watch?v=XXseiON9CV0
이 유투브 영상 보시면 이해가 되실 것 같습니다.

2023-01-09 13:48 UTC, ReturnReason commented
> > > > 전체적으로 확인하시느라 고생하셨어요 👏👏
> > > > 해당 부분은 제가 경험이 없어서 궁금합니다! `JWT`는 보통 프론트에서 암호화해서 사용하는 건가요~?
> > > 
> > > 
> > > 아닙니다! 일반적이지 않아요! JWT는 누구나 까볼 수 있고, 안에 아이디랑 비밀번호가 들어있기 때문에 그냥 스토리지에 저장하면 위험할 것 같아서 암호화를 하여 저장한 겁니다. 그나마 조금 보안을 신경쓴다고 한건데, 저게 나은 방향인지는 잘 모르겠습니다.
> > 
> > 
> > JWT에 비밀번호를 실어 보내나요..? 그렇다면 디코딩해서 말씀하신 것처럼 문제가 될 수 있을 것 같은데요ㅠㅠ 유저를 식별 가능할 수 있는 key라던가, id 같은 내용만 실어 보내야 하지 않나요??
> 
> 비밀번호가 들어 있는건 맞습니다.. 근데 그걸 알아내는 방법은 secret키로 아이디 및 비밀번호가 생성되어서 secret키를 알지 못하면 비밀번호가 유출되는 일은 없을겁니다. 현재 저희 로직도 비밀번호가 변경되면 새로 토큰을 발급해주는 이유도 거기에 있습니다. 토큰에 비밀번호가 포함되어 있기 때문입니다. https://www.youtube.com/watch?v=XXseiON9CV0 이 유투브 영상 보시면 이해가 되실 것 같습니다.

JWT에 payload에 개인정보와 관련된 비밀번호 등은 실어보내면 안됩니다.

2023-01-09 13:48 UTC, vjvl95 commented
> > > > > 전체적으로 확인하시느라 고생하셨어요 👏👏
> > > > > 해당 부분은 제가 경험이 없어서 궁금합니다! `JWT`는 보통 프론트에서 암호화해서 사용하는 건가요~?
> > > > 
> > > > 
> > > > 아닙니다! 일반적이지 않아요! JWT는 누구나 까볼 수 있고, 안에 아이디랑 비밀번호가 들어있기 때문에 그냥 스토리지에 저장하면 위험할 것 같아서 암호화를 하여 저장한 겁니다. 그나마 조금 보안을 신경쓴다고 한건데, 저게 나은 방향인지는 잘 모르겠습니다.
> > > 
> > > 
> > > JWT에 비밀번호를 실어 보내나요..? 그렇다면 디코딩해서 말씀하신 것처럼 문제가 될 수 있을 것 같은데요ㅠㅠ 유저를 식별 가능할 수 있는 key라던가, id 같은 내용만 실어 보내야 하지 않나요??
> > 
> > 
> > 비밀번호가 들어 있는건 맞습니다.. 근데 그걸 알아내는 방법은 secret키로 아이디 및 비밀번호가 생성되어서 secret키를 알지 못하면 비밀번호가 유출되는 일은 없을겁니다. 현재 저희 로직도 비밀번호가 변경되면 새로 토큰을 발급해주는 이유도 거기에 있습니다. 토큰에 비밀번호가 포함되어 있기 때문입니다. https://www.youtube.com/watch?v=XXseiON9CV0 이 유투브 영상 보시면 이해가 되실 것 같습니다.
> 
> JWT에 payload에 개인정보와 관련된 비밀번호 등은 실어보내면 안됩니다.

오호 그렇군요. 근데 비번 넘어오는거 어케 아셨나요? 저는 길어서 뭐가 뭔지 모르겠던데?

2023-01-09 13:50 UTC, ReturnReason commented
> > > > > > 전체적으로 확인하시느라 고생하셨어요 👏👏
> > > > > > 해당 부분은 제가 경험이 없어서 궁금합니다! `JWT`는 보통 프론트에서 암호화해서 사용하는 건가요~?
> > > > > 
> > > > > 
> > > > > 아닙니다! 일반적이지 않아요! JWT는 누구나 까볼 수 있고, 안에 아이디랑 비밀번호가 들어있기 때문에 그냥 스토리지에 저장하면 위험할 것 같아서 암호화를 하여 저장한 겁니다. 그나마 조금 보안을 신경쓴다고 한건데, 저게 나은 방향인지는 잘 모르겠습니다.
> > > > 
> > > > 
> > > > JWT에 비밀번호를 실어 보내나요..? 그렇다면 디코딩해서 말씀하신 것처럼 문제가 될 수 있을 것 같은데요ㅠㅠ 유저를 식별 가능할 수 있는 key라던가, id 같은 내용만 실어 보내야 하지 않나요??
> > > 
> > > 
> > > 비밀번호가 들어 있는건 맞습니다.. 근데 그걸 알아내는 방법은 secret키로 아이디 및 비밀번호가 생성되어서 secret키를 알지 못하면 비밀번호가 유출되는 일은 없을겁니다. 현재 저희 로직도 비밀번호가 변경되면 새로 토큰을 발급해주는 이유도 거기에 있습니다. 토큰에 비밀번호가 포함되어 있기 때문입니다. https://www.youtube.com/watch?v=XXseiON9CV0 이 유투브 영상 보시면 이해가 되실 것 같습니다.
> > 
> > 
> > JWT에 payload에 개인정보와 관련된 비밀번호 등은 실어보내면 안됩니다.
> 
> 오호 그렇군요. 근데 비번 넘어오는거 어케 아셨나요? 저는 길어서 뭐가 뭔지 모르겠던데?

JWT는 디코딩이 쉽기 때문에 토큰만 넣어서 돌려도 다 뜹니다..

2023-01-09 13:53 UTC, vjvl95 commented
> > > > > > > 전체적으로 확인하시느라 고생하셨어요 👏👏
> > > > > > > 해당 부분은 제가 경험이 없어서 궁금합니다! `JWT`는 보통 프론트에서 암호화해서 사용하는 건가요~?
> > > > > > 
> > > > > > 
> > > > > > 아닙니다! 일반적이지 않아요! JWT는 누구나 까볼 수 있고, 안에 아이디랑 비밀번호가 들어있기 때문에 그냥 스토리지에 저장하면 위험할 것 같아서 암호화를 하여 저장한 겁니다. 그나마 조금 보안을 신경쓴다고 한건데, 저게 나은 방향인지는 잘 모르겠습니다.
> > > > > 
> > > > > 
> > > > > JWT에 비밀번호를 실어 보내나요..? 그렇다면 디코딩해서 말씀하신 것처럼 문제가 될 수 있을 것 같은데요ㅠㅠ 유저를 식별 가능할 수 있는 key라던가, id 같은 내용만 실어 보내야 하지 않나요??
> > > > 
> > > > 
> > > > 비밀번호가 들어 있는건 맞습니다.. 근데 그걸 알아내는 방법은 secret키로 아이디 및 비밀번호가 생성되어서 secret키를 알지 못하면 비밀번호가 유출되는 일은 없을겁니다. 현재 저희 로직도 비밀번호가 변경되면 새로 토큰을 발급해주는 이유도 거기에 있습니다. 토큰에 비밀번호가 포함되어 있기 때문입니다. https://www.youtube.com/watch?v=XXseiON9CV0 이 유투브 영상 보시면 이해가 되실 것 같습니다.
> > > 
> > > 
> > > JWT에 payload에 개인정보와 관련된 비밀번호 등은 실어보내면 안됩니다.
> > 
> > 
> > 오호 그렇군요. 근데 비번 넘어오는거 어케 아셨나요? 저는 길어서 뭐가 뭔지 모르겠던데?
> 
> JWT는 디코딩이 쉽기 때문에 토큰만 넣어서 돌려도 다 뜹니다.. 그래서 payload에는 최소한 식별 가능한 정보를 넣어야 한다는 얘기였어요.

저는 돌려볼 생각도 안하고 있어서 그냥 토큰오는구나 했지... 한 수 배워 갑니다

2023-01-14 06:39 UTC, merged